export const FETCH_LABTEST_REQUEST = 'FETCH_LABTEST_REQUEST_COM';
export const FETCH_LABTEST_SUCCESS = 'FETCH_LABTEST_SUCCESS_COM';
export const FETCH_LABTEST_FAILURE = 'FETCH_LABTEST_FAILURE_COM';

export const FETCH_LABTEST_CUSTOMIZATION_REQUEST = 'FETCH_LABTEST_CUSTOMIZATION_REQUEST_COM';
export const FETCH_LABTEST_CUSTOMIZATION_SUCCESS = 'FETCH_LABTEST_CUSTOMIZATION_SUCCESS_COM';
export const FETCH_LABTEST_CUSTOMIZATION_FAILURE = 'FETCH_LABTEST_CUSTOMIZATION_FAILURE_COM';

export const LABTEST_CUSTOMIZATION_REQUEST = 'LABTEST_CUSTOMIZATION_REQUEST_COM';
export const LABTEST_CUSTOMIZATION_SUCCESS = 'LABTEST_CUSTOMIZATION_SUCCESS_COM';
export const LABTEST_CUSTOMIZATION_FAILURE = 'LABTEST_CUSTOMIZATION_FAILURE_COM';

export const DELETE_LABTEST_REQUEST = 'DELETE_LABTEST_REQUEST_COM';
export const DELETE_LABTEST_SUCCESS = 'DELETE_LABTEST_SUCCESS_COM';
export const DELETE_LABTEST_FAILURE = 'DELETE_LABTEST_FAILURE_COM';

export const FETCH_UNIT_LIST_REQUEST = 'FETCH_UNIT_LIST_REQUEST_COM';
export const FETCH_UNIT_LIST_SUCCESS = 'FETCH_UNIT_LIST_SUCCESS_COM';
export const FETCH_UNIT_LIST_FAILURE = 'FETCH_UNIT_LIST_FAILURE_COM';

export const VALIDATE_LABTEST_REQUEST = 'VALIDATE_LABTEST_REQUEST_COM';
export const VALIDATE_LABTEST_SUCCESS = 'VALIDATE_LABTEST_SUCCESS_COM';
export const VALIDATE_LABTEST_FAILURE = 'VALIDATE_LABTEST_FAILURE_COM';
