export const FETCH_COUNTY_LIST_REQUEST = 'FETCH_COUNTY_LIST_REQUEST';
export const FETCH_COUNTY_LIST_SUCCESS = 'FETCH_COUNTY_LIST_SUCCESS';
export const FETCH_COUNTY_LIST_FAILURE = 'FETCH_COUNTY_LIST_FAILURE';

export const CREATE_COUNTY_REQUEST = 'CREATE_COUNTY_REQUEST';
export const CREATE_COUNTY_SUCCESS = 'CREATE_COUNTY_SUCCESS';
export const CREATE_COUNTY_FAILURE = 'CREATE_COUNTY_FAILURE';

export const CREATE_COUNTY_ADMIN_FAIL = 'CREATE_COUNTY_ADMIN_FAIL';
export const FETCH_COUNTY_DETAIL_REQUEST = 'FETCH_COUNTY_DETAIL_REQUEST';
export const SEACRH_COUNTY_USER_SUCCESS = 'SEACRH_COUNTY_USER_SUCCESS';
export const FETCH_COUNTY_DETAIL_SUCCESS = 'FETCH_COUNTY_DETAIL_SUCCESS';
export const FETCH_COUNTY_DETAIL_FAILURE = 'FETCH_COUNTY_DETAIL_FAILURE';

export const FETCH_COUNTY_DASHBOARD_LIST_REQUEST = 'FETCH_COUNTY_DASHBOARD_LIST_REQUEST';
export const FETCH_COUNTY_DASHBOARD_LIST_SUCCESS = 'FETCH_COUNTY_DASHBOARD_LIST_SUCCESS';
export const FETCH_COUNTY_DASHBOARD_LIST_FAIL = 'FETCH_COUNTY_DASHBOARD_LIST_FAIL';

export const UPDATE_COUNTY_DETAIL_REQUEST = 'UPDATE_COUNTY_DETAIL_REQUEST';
export const UPDATE_COUNTY_DETAIL_SUCCESS = 'UPDATE_COUNTY_DETAIL_SUCCESS';
export const UPDATE_COUNTY_DETAIL_FAIL = 'UPDATE_COUNTY_DETAIL_FAIL';

export const UPDATE_COUNTY_ADMIN_REQUEST = 'UPDATE_COUNTY_ADMIN_REQUEST';
export const UPDATE_COUNTY_ADMIN_SUCCESS = 'UPDATE_COUNTY_ADMIN_SUCCESS';
export const UPDATE_COUNTY_ADMIN_FAIL = 'UPDATE_COUNTY_ADMIN_FAIL';

export const CREATE_COUNTY_ADMIN_REQUEST = 'CREATE_COUNTY_ADMIN_REQUEST';
export const CREATE_COUNTY_ADMIN_SUCCESS = 'CREATE_COUNTY_ADMIN_SUCCESS';

export const DELETE_COUNTY_ADMIN_REQUEST = 'DELETE_COUNTY_ADMIN_REQUEST';
export const DELETE_COUNTY_ADMIN_SUCCESS = 'DELETE_COUNTY_ADMIN_SUCCESS';
export const DELETE_COUNTY_ADMIN_FAIL = 'DELETE_COUNTY_ADMIN_FAIL';

export const ACTIVATE_COUNTY_REQUEST = 'ACTIVATE_COUNTY_REQUEST';
export const ACTIVATE_COUNTY_SUCCESS = 'ACTIVATE_COUNTY_SUCCESS';
export const ACTIVATE_COUNTY_FAIL = 'ACTIVATE_COUNTY_FAIL';

export const REMOVE_DEACTIVATED_COUNTY_LIST = 'REMOVE_DEACTIVATED_COUNTY_LIST';

export const DEACTIVATE_COUNTY_REQUEST = 'DEACTIVATE_COUNTY_REQUEST';
export const DEACTIVATE_COUNTY_SUCCESS = 'DEACTIVATE_COUNTY_SUCCESS';
export const DEACTIVATE_COUNTY_FAIL = 'DEACTIVATE_COUNTY_FAIL';

export const FETCH_COUNTY_OPTIONS_REQUEST = 'FETCH_COUNTY_OPTIONS_REQUEST';
export const FETCH_COUNTY_OPTIONS_SUCCESS = 'FETCH_COUNTY_OPTIONS_SUCCESS';
export const FETCH_COUNTY_OPTIONS_FAILURE = 'FETCH_COUNTY_OPTIONS_FAILURE';

export const CLEAR_COUNTY_DETAILS = 'CLEAR_COUNTY_DETAILS';

export const SET_COUNTY_DETAILS = 'SET_COUNTY_DETAILS';

export const CLEAR_COUNTY_LIST = 'CLEAR_COUNTY_LIST';

export const CLEAR_COUNTY_ADMIN = 'CLEAR_COUNTY_ADMIN';

export const FETCH_CLINICAL_WORKFLOW_REQUEST = 'FETCH_CLINICAL_WORKFLOW_REQUEST';
export const FETCH_CLINICAL_WORKFLOW_SUCCESS = 'FETCH_CLINICAL_WORKFLOW_SUCCESS';
export const FETCH_CLINICAL_WORKFLOW_FAILURE = 'FETCH_CLINICAL_WORKFLOW_FAILURE';

export const CREATE_COUNTY_WORKFLOW_MODULE_REQUEST = 'CREATE_COUNTY_WORKFLOW_MODULE_REQUEST';
export const CREATE_COUNTY_WORKFLOW_MODULE_SUCCESS = 'CREATE_COUNTY_WORKFLOW_MODULE_SUCCESS';
export const CREATE_COUNTY_WORKFLOW_MODULE_FAILURE = 'CREATE_COUNTY_WORKFLOW_MODULE_FAILURE';

export const UPDATE_COUNTY_WORKFLOW_MODULE_REQUEST = 'UPDATE_COUNTY_WORKFLOW_MODULE_REQUEST';
export const UPDATE_COUNTY_WORKFLOW_MODULE_SUCCESS = 'UPDATE_COUNTY_WORKFLOW_MODULE_SUCCESS';
export const UPDATE_COUNTY_WORKFLOW_MODULE_FAILURE = 'UPDATE_COUNTY_WORKFLOW_MODULE_FAILURE';

export const DELETE_COUNTY_WORKFLOW_MODULE_REQUEST = 'DELETE_COUNTY_WORKFLOW_MODULE_REQUEST';
export const DELETE_COUNTY_WORKFLOW_MODULE_SUCCESS = 'DELETE_COUNTY_WORKFLOW_MODULE_SUCCESS';
export const DELETE_COUNTY_WORKFLOW_MODULE_FAILURE = 'DELETE_COUNTY_WORKFLOW_MODULE_FAILURE';

export const RESET_CLINICAL_WORKFLOW_REQUEST = 'RESET_CLINICAL_WORKFLOW_REQUEST';
