export const FETCH_LABTEST_REQUEST = 'FETCH_LABTEST_REQUEST';
export const FETCH_LABTEST_SUCCESS = 'FETCH_LABTEST_SUCCESS';
export const FETCH_LABTEST_FAILURE = 'FETCH_LABTEST_FAILURE';

export const FETCH_LABTEST_CUSTOMIZATION_REQUEST = 'FETCH_LABTEST_CUSTOMIZATION_REQUEST';
export const FETCH_LABTEST_CUSTOMIZATION_SUCCESS = 'FETCH_LABTEST_CUSTOMIZATION_SUCCESS';
export const FETCH_LABTEST_CUSTOMIZATION_FAILURE = 'FETCH_LABTEST_CUSTOMIZATION_FAILURE';

export const LABTEST_CUSTOMIZATION_REQUEST = 'LABTEST_CUSTOMIZATION_REQUEST';
export const LABTEST_CUSTOMIZATION_SUCCESS = 'LABTEST_CUSTOMIZATION_SUCCESS';
export const LABTEST_CUSTOMIZATION_FAILURE = 'LABTEST_CUSTOMIZATION_FAILURE';

export const DELETE_LABTEST_REQUEST = 'DELETE_LABTEST_REQUEST';
export const DELETE_LABTEST_SUCCESS = 'DELETE_LABTEST_SUCCESS';
export const DELETE_LABTEST_FAILURE = 'DELETE_LABTEST_FAILURE';

export const FETCH_UNIT_LIST_REQUEST = 'FETCH_UNIT_LIST_REQUEST';
export const FETCH_UNIT_LIST_SUCCESS = 'FETCH_UNIT_LIST_SUCCESS';
export const FETCH_UNIT_LIST_FAILURE = 'FETCH_UNIT_LIST_FAILURE';

export const VALIDATE_LABTEST_REQUEST = 'VALIDATE_LABTEST_REQUEST';
export const VALIDATE_LABTEST_SUCCESS = 'VALIDATE_LABTEST_SUCCESS';
export const VALIDATE_LABTEST_FAILURE = 'VALIDATE_LABTEST_FAILURE';
