export const FETCH_HEALTH_FACILITY_LIST_REQUEST_COM = 'FETCH_HEALTH_FACILITY_LIST_REQUEST_COM';
export const FETCH_HEALTH_FACILITY_LIST_SUCCESS = 'FETCH_HEALTH_FACILITY_LIST_SUCCESS_COM';
export const FETCH_HEALTH_FACILITY_LIST_FAILURE = 'FETCH_HEALTH_FACILITY_LIST_FAILURE_COM';

export const FETCH_INSIGHT_HEALTH_FACILITY_LIST_REQUEST = 'FETCH_INSIGHT_HEALTH_FACILITY_LIST_REQUEST_COM';
export const FETCH_INSIGHT_HEALTH_FACILITY_LIST_SUCCESS = 'FETCH_INSIGHT_HEALTH_FACILITY_LIST_SUCCESS_COM';
export const FETCH_INSIGHT_HEALTH_FACILITY_LIST_FAILURE = 'FETCH_INSIGHT_HEALTH_FACILITY_LIST_FAILURE_COM';

export const CLEAR_HEALTH_FACILITY_LIST = 'CLEAR_HEALTH_FACILITY_LIST_COM';

export const CREATE_HEALTH_FACILITY_REQUEST = 'CREATE_HEALTH_FACILITY_REQUEST_COM';
export const CREATE_HEALTH_FACILITY_SUCCESS = 'CREATE_HEALTH_FACILITY_SUCCESS_COM';
export const CREATE_HEALTH_FACILITY_FAILURE = 'CREATE_HEALTH_FACILITY_FAILURE_COM';

export const DELETE_HEALTH_FACILITY_REQUEST = 'DELETE_HEALTH_FACILITY_REQUEST_COM';
export const DELETE_HEALTH_FACILITY_SUCCESS = 'DELETE_HEALTH_FACILITY_SUCCESS_COM';
export const DELETE_HEALTH_FACILITY_FAILURE = 'DELETE_HEALTH_FACILITY_FAILURE_COM';

export const FETCH_HEALTH_FACILITY_TYPES_REQUEST = 'FETCH_HEALTH_FACILITY_TYPES_REQUEST_COM';
export const FETCH_HEALTH_FACILITY_TYPES_SUCCESS = 'FETCH_HEALTH_FACILITY_TYPES_SUCCESS_COM';
export const FETCH_HEALTH_FACILITY_TYPES_FAILURE = 'FETCH_HEALTH_FACILITY_TYPES_FAILURE_COM';

export const UPDATE_HEALTH_FACILITY_DETAILS_REQUEST = 'UPDATE_HEALTH_FACILITY_DETAILS_REQUEST_COM';
export const UPDATE_HEALTH_FACILITY_DETAILS_SUCCESS = 'UPDATE_HEALTH_FACILITY_DETAILS_SUCCESS_COM';
export const UPDATE_HEALTH_FACILITY_DETAILS_FAILURE = 'UPDATE_HEALTH_FACILITY_DETAILS_FAILURE_COM';

export const FETCH_HEALTH_FACILITY_USER_LIST_REQUEST = 'FETCH_HEALTH_FACILITY_USER_LIST_REQUEST_COM';
export const FETCH_HEALTH_FACILITY_USER_LIST_SUCCESS = 'FETCH_HEALTH_FACILITY_USER_LIST_SUCCESS_COM';
export const FETCH_HEALTH_FACILITY_USER_LIST_FAILURE = 'FETCH_HEALTH_FACILITY_USER_LIST_FAILURE_COM';

export const FETCH_HEALTH_FACILITY_USER_DETAIL_REQUEST = 'FETCH_HEALTH_FACILITY_USER_DETAIL_REQUEST_COM';
export const FETCH_HEALTH_FACILITY_USER_DETAIL_SUCCESS = 'FETCH_HEALTH_FACILITY_USER_DETAIL_SUCCESS_COM';
export const FETCH_HEALTH_FACILITY_USER_DETAIL_FAILURE = 'FETCH_HEALTH_FACILITY_USER_DETAIL_FAILURE_COM';

export const DELETE_HEALTH_FACILITY_USER_REQUEST = 'DELETE_HEALTH_FACILITY_USER_REQUEST_COM';
export const DELETE_HEALTH_FACILITY_USER_SUCCESS = 'DELETE_HEALTH_FACILITY_USER_SUCCESS_COM';
export const DELETE_HEALTH_FACILITY_USER_FAILURE = 'DELETE_HEALTH_FACILITY_USER_FAILURE_COM';

export const CREATE_HEALTH_FACILITY_USER_REQUEST = 'CREATE_HEALTH_FACILITY_USER_REQUEST_COM';
export const CREATE_HEALTH_FACILITY_USER_SUCCESS = 'CREATE_HEALTH_FACILITY_USER_SUCCESS_COM';
export const CREATE_HEALTH_FACILITY_USER_FAILURE = 'CREATE_HEALTH_FACILITY_USER_FAILURE_COM';

export const UPDATE_HEALTH_FACILITY_USER_REQUEST = 'UPDATE_HEALTH_FACILITY_USER_REQUEST_COM';
export const UPDATE_HEALTH_FACILITY_USER_SUCCESS = 'UPDATE_HEALTH_FACILITY_USER_SUCCESS_COM';
export const UPDATE_HEALTH_FACILITY_USER_FAILURE = 'UPDATE_HEALTH_FACILITY_USER_FAILURE_COM';

export const FETCH_HEALTH_FACILITY_SUMMARY_REQUEST = 'FETCH_HEALTH_FACILITY_SUMMARY_REQUEST_COM';
export const FETCH_HEALTH_FACILITY_SUMMARY_SUCCESS = 'FETCH_HEALTH_FACILITY_SUMMARY_SUCCESS_COM';
export const FETCH_HEALTH_FACILITY_SUMMARY_FAILURE = 'FETCH_HEALTH_FACILITY_SUMMARY_FAILURE_COM';

export const FETCH_HEALTH_FACILITY_USERS_REQUEST = 'FETCH_HEALTH_FACILITY_USERS_REQUEST_COM';
export const FETCH_HEALTH_FACILITY_USERS_SUCCESS = 'FETCH_HEALTH_FACILITY_USERS_SUCCESS_COM';
export const FETCH_HEALTH_FACILITY_USERS_FAILURE = 'FETCH_HEALTH_FACILITY_USERS_FAILURE_COM';

export const FETCH_CHIEFDOM_LIST_REQUEST = 'FETCH_CHIEFDOM_LIST_REQUEST_COM';
export const FETCH_CHIEFDOM_LIST_SUCCESS = 'FETCH_CHIEFDOM_LIST_SUCCESS_COM';
export const FETCH_CHIEFDOM_LIST_FAILURE = 'FETCH_CHIEFDOM_LIST_FAILURE_COM';

export const FETCH_DISTRICT_LIST_REQUEST = 'FETCH_DISTRICT_LIST_REQUEST_COM';
export const FETCH_DISTRICT_LIST_SUCCESS = 'FETCH_DISTRICT_LIST_SUCCESS_COM';
export const FETCH_DISTRICT_LIST_FAILURE = 'FETCH_DISTRICT_LIST_FAILURE_COM';

export const FETCH_VILLAGES_LIST_REQUEST = 'FETCH_VILLAGES_LIST_REQUEST_COM';
export const FETCH_VILLAGES_LIST_SUCCESS = 'FETCH_VILLAGES_LIST_SUCCESS_COM';
export const FETCH_VILLAGES_LIST_FAILURE = 'FETCH_VILLAGES_LIST_FAILURE_COM';

export const FETCH_UNLINKED_VILLAGES_REQUEST = 'FETCH_UNLINKED_VILLAGES_REQUEST_COM';
export const FETCH_UNLINKED_VILLAGES_SUCCESS = 'FETCH_UNLINKED_VILLAGES_SUCCESS_COM';
export const FETCH_UNLINKED_VILLAGES_FAILURE = 'FETCH_UNLINKED_VILLAGES_FAILURE_COM';

export const FETCH_VILLAGES_LIST_FROM_HF_REQUEST = 'FETCH_VILLAGES_LIST_FROM_HF_REQUEST_COM';
export const FETCH_VILLAGES_LIST_FROM_HF_SUCCESS = 'FETCH_VILLAGES_LIST_FROM_HF_SUCCESS_COM';
export const FETCH_VILLAGES_LIST_FROM_HF_FAILURE = 'FETCH_VILLAGES_LIST_FROM_HF_FAILURE_COM';

export const CLEAR_HF_FORM_DATA = 'CLEAR_HF_FORM_DATA_COM';
export const CLEAR_ALL_DEPENDENT_DATA = 'CLEAR_ALL_DEPENDENT_DATA_COM';
export const CLEAR_VILLAGES_LIST_FROM_HF = 'CLEAR_VILLAGES_LIST_FROM_HF_COM';
export const CLEAR_VILLAGES_LIST = 'CLEAR_VILLAGES_LIST_COM';

export const FETCH_PEER_SUPERVISOR_LIST_REQUEST = 'FETCH_PEER_SUPERVISOR_LIST_REQUEST_COM';
export const FETCH_PEER_SUPERVISOR_LIST_SUCCESS = 'FETCH_PEER_SUPERVISOR_LIST_SUCCESS_COM';
export const FETCH_PEER_SUPERVISOR_LIST_FAILURE = 'FETCH_PEER_SUPERVISOR_LIST_FAILURE_COM';

export const CLEAR_PEER_SUPERVISOR_LIST = 'CLEAR_PEER_SUPERVISOR_LIST_COM';

export const CLEAR_HEALTH_FACILITY_DETAIL = 'CLEAR_HEALTH_FACILITY_DETAIL_COM';

export const FETCH_WORKFLOW_LIST_REQUEST = 'FETCH_WORKFLOW_LIST_REQUEST_COM';
export const FETCH_WORKFLOW_LIST_SUCCESS = 'FETCH_WORKFLOW_LIST_SUCCESS_COM';
export const FETCH_WORKFLOW_LIST_FAILURE = 'FETCH_WORKFLOW_LIST_FAILURE_COM';

export const LINKED_RESTRICTIONS_VALIDATION_REQUEST = 'LINKED_RESTRICTIONS_VALIDATION_REQUEST_COM';
export const LINKED_RESTRICTIONS_VALIDATION_SUCCESS = 'LINKED_RESTRICTIONS_VALIDATION_SUCCESS_COM';
export const LINKED_RESTRICTIONS_VALIDATION_FAILURE = 'LINKED_RESTRICTIONS_VALIDATION_FAILURE_COM';

export const FETCH_CULTURE_LIST_REQUEST = 'FETCH_CULTURE_LIST_REQUEST_COM';
export const FETCH_CULTURE_LIST_SUCCESS = 'FETCH_CULTURE_LIST_SUCCESS_COM';
export const FETCH_CULTURE_LIST_FAILURE = 'FETCH_CULTURE_LIST_FAILURE_COM';

export const FETCH_COUNTRY_LIST_REQUEST = 'FETCH_COUNTRY_LIST_REQUEST_COM';
export const FETCH_COUNTRY_LIST_SUCCESS = 'FETCH_COUNTRY_LIST_SUCCESS_COM';
export const FETCH_COUNTRY_LIST_FAILURE = 'FETCH_COUNTRY_LIST_FAILURE_COM';
