export const FETCH_SUB_COUNTY_DASHBOARD_LIST_REQUEST = 'FETCH_SUB_COUNTY_DASHBOARD_LIST_REQUEST';
export const FETCH_SUB_COUNTY_DASHBOARD_LIST_SUCCESS = 'FETCH_SUB_COUNTY_DASHBOARD_LIST_SUCCESS';
export const FETCH_SUB_COUNTY_DASHBOARD_LIST_FAILURE = 'FETCH_SUB_COUNTY_DASHBOARD_LIST_FAILURE';

export const FETCH_SUB_COUNTY_DETAIL_REQUEST = 'FETCH_SUB_COUNTY_DETAIL_REQUEST';
export const FETCH_SUB_COUNTY_DETAIL_SUCCESS = 'FETCH_SUB_COUNTY_DETAIL_SUCCESS';
export const FETCH_SUB_COUNTY_DETAIL_FAILURE = 'FETCH_SUB_COUNTY_DETAIL_FAILURE';

export const SEARCH_SUB_COUNTY_USER_SUCCESS = 'SEARCH_SUB_COUNTY_USER_SUCCESS';

export const FETCH_SUB_COUNTY_LIST_REQUEST = 'FETCH_SUB_COUNTY_LIST_REQUEST';
export const FETCH_SUB_COUNTY_LIST_SUCCESS = 'FETCH_SUB_COUNTY_LIST_SUCCESS';
export const FETCH_SUB_COUNTY_LIST_FAILURE = 'FETCH_SUB_COUNTY_LIST_FAILURE';

export const CREATE_SUB_COUNTY_REQUEST = 'CREATE_SUB_COUNTY_REQUEST';
export const CREATE_SUB_COUNTY_SUCCESS = 'CREATE_SUB_COUNTY_SUCCESS';
export const CREATE_SUB_COUNTY_FAILURE = 'CREATE_SUB_COUNTY_FAILURE';

export const UPDATE_SUB_COUNTY_REQUEST = 'UPDATE_SUB_COUNTY_REQUEST';
export const UPDATE_SUB_COUNTY_SUCCESS = 'UPDATE_SUB_COUNTY_SUCCESS';
export const UPDATE_SUB_COUNTY_FAILURE = 'UPDATE_SUB_COUNTY_FAILURE';

export const UPDATE_SUB_COUNTY_ADMIN_REQUEST = 'UPDATE_SUB_COUNTY_ADMIN_REQUEST';
export const UPDATE_SUB_COUNTY_ADMIN_SUCCESS = 'UPDATE_SUB_COUNTY_ADMIN_SUCCESS';
export const UPDATE_SUB_COUNTY_ADMIN_FAILURE = 'UPDATE_SUB_COUNTY_ADMIN_FAILURE';

export const CREATE_SUB_COUNTY_ADMIN_REQUEST = 'CREATE_SUB_COUNTY_ADMIN_REQUEST';
export const CREATE_SUB_COUNTY_ADMIN_SUCCESS = 'CREATE_SUB_COUNTY_ADMIN_SUCCESS';
export const CREATE_SUB_COUNTY_ADMIN_FAILURE = 'CREATE_SUB_COUNTY_ADMIN_FAILURE';

export const DELETE_SUB_COUNTY_ADMIN_REQUEST = 'DELETE_SUB_COUNTY_ADMIN_REQUEST';
export const DELETE_SUB_COUNTY_ADMIN_SUCCESS = 'DELETE_SUB_COUNTY_ADMIN_SUCCESS';
export const DELETE_SUB_COUNTY_ADMIN_FAILURE = 'DELETE_SUB_COUNTY_ADMIN_FAILURE';

export const FETCH_SUB_COUNTY_BY_ID_REQUEST = 'FETCH_SUB_COUNTY_BY_ID_REQUEST';
export const FETCH_SUB_COUNTY_BY_ID_SUCCESS = 'FETCH_SUB_COUNTY_BY_ID_SUCCESS';
export const FETCH_SUB_COUNTY_BY_ID_FAILURE = 'FETCH_SUB_COUNTY_BY_ID_FAILURE';

export const FETCH_SUB_COUNTY_ADMIN_BY_ID_REQUEST = 'FETCH_SUB_COUNTY_ADMIN_BY_ID_REQUEST';
export const FETCH_SUB_COUNTY_ADMIN_BY_ID_SUCCESS = 'FETCH_SUB_COUNTY_ADMIN_BY_ID_SUCCESS';
export const FETCH_SUB_COUNTY_ADMIN_BY_ID_FAILURE = 'FETCH_SUB_COUNTY_ADMIN_BY_ID_FAILURE';

export const FETCH_SUB_COUNTY_ADMIN_LIST_REQUEST = 'FETCH_SUB_COUNTY_ADMIN_LIST_REQUEST';
export const FETCH_SUB_COUNTY_ADMIN_LIST_SUCCESS = 'FETCH_SUB_COUNTY_ADMIN_LIST_SUCCESS';
export const FETCH_SUB_COUNTY_ADMIN_LIST_FAILURE = 'FETCH_SUB_COUNTY_ADMIN_LIST_FAILURE';

export const CLEAR_SUB_COUNTY_DETAIL = 'CLEAR_SUB_COUNTY_DETAIL';

export const SET_SUB_COUNTY_DETAILS = 'SET_SUB_COUNTY_DETAILS';

export const CLEAR_SUB_COUNTY_LIST = 'CLEAR_SUB_COUNTY_LIST';

export const CLEAR_SUB_COUNTY_ADMIN_LIST = 'CLEAR_SUB_COUNTY_ADMIN_LIST';

export const FETCH_SUB_COUNTY_DROPDOWN_REQUEST = 'FETCH_SUB_COUNTY_DROPDOWN_REQUEST';
export const FETCH_SUB_COUNTY_DROPDOWN_SUCCESS = 'FETCH_SUB_COUNTY_DROPDOWN_SUCCESS';
export const FETCH_SUB_COUNTY_DROPDOWN_FAIL = 'FETCH_SUB_COUNTY_DROPDOWN_FAIL';

export const CLEAR_DROPDOWN_VALUES = 'CLEAR_DROPDOWN_VALUES';
