export const FETCH_HEALTH_FACILITY_LIST_REQUEST = 'FETCH_HEALTH_FACILITY_LIST_REQUEST';
export const FETCH_HEALTH_FACILITY_LIST_SUCCESS = 'FETCH_HEALTH_FACILITY_LIST_SUCCESS';
export const FETCH_HEALTH_FACILITY_LIST_FAILURE = 'FETCH_HEALTH_FACILITY_LIST_FAILURE';

export const CREATE_HEALTH_FACILITY_REQUEST = 'CREAT_HEALTH_FACILITY_REQUEST';
export const CREATE_HEALTH_FACILITY_SUCCESS = 'CREAT_HEALTH_FACILITY_SUCCESS';
export const CREATE_HEALTH_FACILITY_FAILURE = 'CREAT_HEALTH_FACILITY_FAILURE';

export const FETCH_COUNTY_DROPDOWN_REQUEST = 'FETCH_COUNTY_DROPDOWN_REQUEST';
export const FETCH_COUNTY_DROPDOWN_SUCCESS = 'FETCH_COUNTY_DROPDOWN_SUCCESS';
export const FETCH_COUNTY_DROPDOWN_FAILURE = 'FETCH_COUNTY_DROPDOWN_FAILURE';

export const FETCH_SUB_COUNTY_DROPDOWN_REQUEST = 'FETCH_SUB_COUNTY_DROPDOWN_REQUEST';
export const FETCH_SUB_COUNTY_DROPDOWN_SUCCESS = 'FETCH_SUB_COUNTY_DROPDOWN_SUCCESS';
export const FETCH_SUB_COUNTY_DROPDOWN_FAILURE = 'FETCH_SUB_COUNTY_DROPDOWN_FAILURE';

export const FETCH_CULTURE_DROPDOWN_REQUEST = 'FETCH_CULTURE_DROPDOWN_REQUEST';
export const FETCH_CULTURE_DROPDOWN_SUCCESS = 'FETCH_CULTURE_DROPDOWN_SUCCESS';
export const FETCH_CULTURE_DROPDOWN_FAILURE = 'FETCH_CULTURE_DROPDOWN_FAILURE';

export const CLEAR_DROPDOWN_VALUES = 'CLEAR_DROPDOWN_VALUES';

export const UPDATE_HEALTH_FACILITY_DETAILS_REQUEST = 'UPDATE_HEALTH_FACILITY_DETAILS_REQUEST';
export const UPDATE_HEALTH_FACILITY_DETAILS_SUCCESS = 'UPDATE_HEALTH_FACILITY_DETAILS_SUCCESS';
export const UPDATE_HEALTH_FACILITY_DETAILS_FAILURE = 'UPDATE_HEALTH_FACILITY_DETAILS_FAILURE';

export const FETCH_HEALTH_FACILITY_USER_LIST_REQUEST = 'FETCH_HEALTH_FACILITY_USER_LIST_REQUEST';
export const FETCH_HEALTH_FACILITY_USER_LIST_SUCCESS = 'FETCH_HEALTH_FACILITY_USER_LIST_SUCCESS';
export const FETCH_HEALTH_FACILITY_USER_LIST_FAILURE = 'FETCH_HEALTH_FACILITY_USER_LIST_FAILURE';

export const DELETE_HEALTH_FACILITY_USER_REQUEST = 'DELETE_HEALTH_FACILITY_USER_REQUEST';
export const DELETE_HEALTH_FACILITY_USER_SUCCESS = 'DELETE_HEALTH_FACILITY_USER_SUCCESS';
export const DELETE_HEALTH_FACILITY_USER_FAILURE = 'DELETE_HEALTH_FACILITY_USER_FAILURE';

export const CREATE_HEALTH_FACILITY_USER_REQUEST = 'CREATE_HEALTH_FACILITY_USER_REQUEST';
export const CREATE_HEALTH_FACILITY_USER_SUCCESS = 'CREATE_HEALTH_FACILITY_USER_SUCCESS';
export const CREATE_HEALTH_FACILITY_USER_FAILURE = 'CREATE_HEALTH_FACILITY_USER_FAILURE';

export const UPDATE_HEALTH_FACILITY_USER_REQUEST = 'UPDATE_HEALTH_FACILITY_USER_REQUEST';
export const UPDATE_HEALTH_FACILITY_USER_SUCCESS = 'UPDATE_HEALTH_FACILITY_USER_SUCCESS';
export const UPDATE_HEALTH_FACILITY_USER_FAILURE = 'UPDATE_HEALTH_FACILITY_USER_FAILURE';

export const FETCH_HEALTH_FACILITY_SUMMARY_REQUEST = 'FETCH_HEALTH_FACILITY_SUMMARY_REQUEST';
export const FETCH_HEALTH_FACILITY_SUMMARY_SUCCESS = 'FETCH_HEALTH_FACILITY_SUMMARY_SUCCESS';
export const FETCH_HEALTH_FACILITY_SUMMARY_FAILURE = 'FETCH_HEALTH_FACILITY_SUMMARY_FAILURE';

export const FETCH_HEALTH_FACILITY_USERS_REQUEST = 'FETCH_HEALTH_FACILITY_USERS_REQUEST';
export const FETCH_HEALTH_FACILITY_USERS_SUCCESS = 'FETCH_HEALTH_FACILITY_USERS_SUCCESS';
export const FETCH_HEALTH_FACILITY_USERS_FAILURE = 'FETCH_HEALTH_FACILITY_USERS_FAILURE';

export const FETCH_CHIEFDOM_LIST_REQUEST = 'FETCH_CHIEFDOM_LIST_REQUEST';
export const FETCH_CHIEFDOM_LIST_SUCCESS = 'FETCH_CHIEFDOM_LIST_SUCCESS';
export const FETCH_CHIEFDOM_LIST_FAILURE = 'FETCH_CHIEFDOM_LIST_FAILURE';

export const FETCH_DISTRICT_LIST_REQUEST = 'FETCH_DISTRICT_LIST_REQUEST';
export const FETCH_DISTRICT_LIST_SUCCESS = 'FETCH_DISTRICT_LIST_SUCCESS';
export const FETCH_DISTRICT_LIST_FAILURE = 'FETCH_DISTRICT_LIST_FAILURE';

export const FETCH_VILLAGES_LIST_REQUEST = 'FETCH_VILLAGES_LIST_REQUEST';
export const FETCH_VILLAGES_LIST_SUCCESS = 'FETCH_VILLAGES_LIST_SUCCESS';
export const FETCH_VILLAGES_LIST_FAILURE = 'FETCH_VILLAGES_LIST_FAILURE';

export const FETCH_PEER_SUPERVISOR_LIST_REQUEST = 'FETCH_PEER_SUPERVISOR_LIST_REQUEST';
export const FETCH_PEER_SUPERVISOR_LIST_SUCCESS = 'FETCH_PEER_SUPERVISOR_LIST_SUCCESS';
export const FETCH_PEER_SUPERVISOR_LIST_FAILURE = 'FETCH_PEER_SUPERVISOR_LIST_FAILURE';

export const FETCH_WORKFLOW_LIST_REQUEST = 'FETCH_WORKFLOW_LIST_REQUEST';
export const FETCH_WORKFLOW_LIST_SUCCESS = 'FETCH_WORKFLOW_LIST_SUCCESS';
export const FETCH_WORKFLOW_LIST_FAILURE = 'FETCH_WORKFLOW_LIST_FAILURE';
