export const FETCH_HEALTH_FACILITY_LIST_REQUEST = 'FETCH_HEALTH_FACILITY_LIST_REQUEST';
export const FETCH_HEALTH_FACILITY_LIST_SUCCESS = 'FETCH_HEALTH_FACILITY_LIST_SUCCESS';
export const FETCH_HEALTH_FACILITY_LIST_FAILURE = 'FETCH_HEALTH_FACILITY_LIST_FAILURE';

export const SET_ASSIGNED_HF_LIST_FOR_HF_ADMIN = 'SET_ASSIGNED_HF_LIST_FOR_HF_ADMIN';
export const CLEAR_ASSIGNED_HF_LIST_FOR_HF_ADMIN = 'CLEAR_ASSIGNED_HF_LIST_FOR_HF_ADMIN';

export const FETCH_VILLAGES_LIST_USER_LINKED = 'FETCH_VILLAGES_LIST_USER_LINKED';

export const CLEAR_HEALTH_FACILITY_LIST = 'CLEAR_HEALTH_FACILITY_LIST';

export const CREATE_HEALTH_FACILITY_REQUEST = 'CREATE_HEALTH_FACILITY_REQUEST';
export const CREATE_HEALTH_FACILITY_SUCCESS = 'CREATE_HEALTH_FACILITY_SUCCESS';
export const CREATE_HEALTH_FACILITY_FAILURE = 'CREATE_HEALTH_FACILITY_FAILURE';

export const DELETE_HEALTH_FACILITY_REQUEST = 'DELETE_HEALTH_FACILITY_REQUEST';
export const DELETE_HEALTH_FACILITY_SUCCESS = 'DELETE_HEALTH_FACILITY_SUCCESS';
export const DELETE_HEALTH_FACILITY_FAILURE = 'DELETE_HEALTH_FACILITY_FAILURE';

export const FETCH_HEALTH_FACILITY_TYPES_REQUEST = 'FETCH_HEALTH_FACILITY_TYPES_REQUEST';
export const FETCH_HEALTH_FACILITY_TYPES_SUCCESS = 'FETCH_HEALTH_FACILITY_TYPES_SUCCESS';
export const FETCH_HEALTH_FACILITY_TYPES_FAILURE = 'FETCH_HEALTH_FACILITY_TYPES_FAILURE';

export const UPDATE_HEALTH_FACILITY_DETAILS_REQUEST = 'UPDATE_HEALTH_FACILITY_DETAILS_REQUEST';
export const UPDATE_HEALTH_FACILITY_DETAILS_SUCCESS = 'UPDATE_HEALTH_FACILITY_DETAILS_SUCCESS';
export const UPDATE_HEALTH_FACILITY_DETAILS_FAILURE = 'UPDATE_HEALTH_FACILITY_DETAILS_FAILURE';

export const FETCH_HEALTH_FACILITY_USER_LIST_REQUEST = 'FETCH_HEALTH_FACILITY_USER_LIST_REQUEST';
export const FETCH_HEALTH_FACILITY_USER_LIST_SUCCESS = 'FETCH_HEALTH_FACILITY_USER_LIST_SUCCESS';
export const FETCH_HEALTH_FACILITY_USER_LIST_FAILURE = 'FETCH_HEALTH_FACILITY_USER_LIST_FAILURE';
export const FETCH_HEALTH_FACILITY_USER_CLEAR_LIST_REQUEST = 'FETCH_HEALTH_FACILITY_USER_CLEAR_LIST_REQUEST';

export const FETCH_HEALTH_FACILITY_USER_DETAIL_REQUEST = 'FETCH_HEALTH_FACILITY_USER_DETAIL_REQUEST';
export const FETCH_HEALTH_FACILITY_USER_DETAIL_SUCCESS = 'FETCH_HEALTH_FACILITY_USER_DETAIL_SUCCESS';
export const FETCH_HEALTH_FACILITY_USER_DETAIL_FAILURE = 'FETCH_HEALTH_FACILITY_USER_DETAIL_FAILURE';

export const DELETE_HEALTH_FACILITY_USER_REQUEST = 'DELETE_HEALTH_FACILITY_USER_REQUEST';
export const DELETE_HEALTH_FACILITY_USER_SUCCESS = 'DELETE_HEALTH_FACILITY_USER_SUCCESS';
export const DELETE_HEALTH_FACILITY_USER_FAILURE = 'DELETE_HEALTH_FACILITY_USER_FAILURE';

export const CREATE_HEALTH_FACILITY_USER_REQUEST = 'CREATE_HEALTH_FACILITY_USER_REQUEST';
export const CREATE_HEALTH_FACILITY_USER_SUCCESS = 'CREATE_HEALTH_FACILITY_USER_SUCCESS';
export const CREATE_HEALTH_FACILITY_USER_FAILURE = 'CREATE_HEALTH_FACILITY_USER_FAILURE';

export const UPDATE_HEALTH_FACILITY_USER_REQUEST = 'UPDATE_HEALTH_FACILITY_USER_REQUEST';
export const UPDATE_HEALTH_FACILITY_USER_SUCCESS = 'UPDATE_HEALTH_FACILITY_USER_SUCCESS';
export const UPDATE_HEALTH_FACILITY_USER_FAILURE = 'UPDATE_HEALTH_FACILITY_USER_FAILURE';

export const FETCH_HEALTH_FACILITY_SUMMARY_REQUEST = 'FETCH_HEALTH_FACILITY_SUMMARY_REQUEST';
export const FETCH_HEALTH_FACILITY_SUMMARY_SUCCESS = 'FETCH_HEALTH_FACILITY_SUMMARY_SUCCESS';
export const FETCH_HEALTH_FACILITY_SUMMARY_FAILURE = 'FETCH_HEALTH_FACILITY_SUMMARY_FAILURE';

export const FETCH_HEALTH_FACILITY_USERS_REQUEST = 'FETCH_HEALTH_FACILITY_USERS_REQUEST';
export const FETCH_HEALTH_FACILITY_USERS_SUCCESS = 'FETCH_HEALTH_FACILITY_USERS_SUCCESS';
export const FETCH_HEALTH_FACILITY_USERS_FAILURE = 'FETCH_HEALTH_FACILITY_USERS_FAILURE';

export const FETCH_CHIEFDOM_LIST_REQUEST_FOR_HF = 'FETCH_CHIEFDOM_LIST_REQUEST_FOR_HF';
export const FETCH_CHIEFDOM_LIST_SUCCESS_FOR_HF = 'FETCH_CHIEFDOM_LIST_SUCCESS_FOR_HF';
export const FETCH_CHIEFDOM_LIST_FAILURE_FOR_HF = 'FETCH_CHIEFDOM_LIST_FAILURE_FOR_HF';

export const FETCH_DISTRICT_LIST_REQUEST_FOR_HF = 'FETCH_DISTRICT_LIST_REQUEST_FOR_HF';
export const FETCH_DISTRICT_LIST_SUCCESS_FOR_HF = 'FETCH_DISTRICT_LIST_SUCCESS_FOR_HF';
export const FETCH_DISTRICT_LIST_FAILURE_FOR_HF = 'FETCH_DISTRICT_LIST_FAILURE_FOR_HF';

export const FETCH_VILLAGES_LIST_REQUEST_FOR_HF = 'FETCH_VILLAGES_LIST_REQUEST_FOR_HF';
export const FETCH_VILLAGES_LIST_SUCCESS_FOR_HF = 'FETCH_VILLAGES_LIST_SUCCESS_FOR_HF';
export const FETCH_VILLAGES_LIST_FAILURE_FOR_HF = 'FETCH_VILLAGES_LIST_FAILURE_FOR_HF';

export const FETCH_CITY_LIST_REQUEST_FOR_HF = 'FETCH_CITY_LIST_REQUEST_FOR_HF';
export const FETCH_CITY_LIST_SUCCESS_FOR_HF = 'FETCH_CITY_LIST_SUCCESS_FOR_HF';
export const FETCH_CITY_LIST_FAILURE_FOR_HF = 'FETCH_CITY_LIST_FAILURE_FOR_HF';

export const FETCH_UNLINKED_VILLAGES_REQUEST = 'FETCH_UNLINKED_VILLAGES_REQUEST';
export const FETCH_UNLINKED_VILLAGES_SUCCESS = 'FETCH_UNLINKED_VILLAGES_SUCCESS';
export const FETCH_UNLINKED_VILLAGES_FAILURE = 'FETCH_UNLINKED_VILLAGES_FAILURE';

export const CLEAR_HF_FORM_DATA = 'CLEAR_HF_FORM_DATA';

export const FETCH_VILLAGES_LIST_FROM_HF_REQUEST = 'FETCH_VILLAGES_LIST_FROM_HF_REQUEST';
export const FETCH_VILLAGES_LIST_FROM_HF_SUCCESS = 'FETCH_VILLAGES_LIST_FROM_HF_SUCCESS';
export const FETCH_VILLAGES_LIST_FROM_HF_FAILURE = 'FETCH_VILLAGES_LIST_FROM_HF_FAILURE';

export const CLEAR_ALL_DEPENDENT_DATA = 'CLEAR_ALL_DEPENDENT_DATA';
export const CLEAR_VILLAGES_LIST_FROM_HF = 'CLEAR_VILLAGES_LIST_FROM_HF';
export const CLEAR_VILLAGES_LIST = 'CLEAR_VILLAGES_LIST';

export const FETCH_PEER_SUPERVISOR_LIST_REQUEST = 'FETCH_PEER_SUPERVISOR_LIST_REQUEST';
export const FETCH_PEER_SUPERVISOR_LIST_SUCCESS = 'FETCH_PEER_SUPERVISOR_LIST_SUCCESS';
export const FETCH_PEER_SUPERVISOR_LIST_FAILURE = 'FETCH_PEER_SUPERVISOR_LIST_FAILURE';

export const CLEAR_PEER_SUPERVISOR_LIST = 'CLEAR_PEER_SUPERVISOR_LIST';

export const CLEAR_HEALTH_FACILITY_DETAIL = 'CLEAR_HEALTH_FACILITY_DETAIL';

export const FETCH_WORKFLOW_LIST_REQUEST = 'FETCH_WORKFLOW_LIST_REQUEST';
export const FETCH_WORKFLOW_LIST_SUCCESS = 'FETCH_WORKFLOW_LIST_SUCCESS';
export const FETCH_WORKFLOW_LIST_FAILURE = 'FETCH_WORKFLOW_LIST_FAILURE';

export const CLEAR_HF_WORKFLOW_LIST = 'CLEAR_HF_WORKFLOW_LIST';

export const FETCH_PEER_SUPERVISOR_VALIDATION = 'FETCH_PEER_SUPERVISOR_VALIDATION';

export const LINKED_RESTRICTIONS_VALIDATION_REQUEST = 'LINKED_RESTRICTIONS_VALIDATION_REQUEST';
export const LINKED_RESTRICTIONS_VALIDATION_SUCCESS = 'LINKED_RESTRICTIONS_VALIDATION_SUCCESS';
export const LINKED_RESTRICTIONS_VALIDATION_FAILURE = 'LINKED_RESTRICTIONS_VALIDATION_FAILURE';

export const FETCH_CULTURE_LIST_REQUEST = 'FETCH_CULTURE_LIST_REQUEST';
export const FETCH_CULTURE_LIST_SUCCESS = 'FETCH_CULTURE_LIST_SUCCESS';
export const FETCH_CULTURE_LIST_FAILURE = 'FETCH_CULTURE_LIST_FAILURE';

export const FETCH_COUNTRY_LIST_REQUEST = 'FETCH_COUNTRY_LIST_REQUEST';
export const FETCH_COUNTRY_LIST_SUCCESS = 'FETCH_COUNTRY_LIST_SUCCESS';
export const FETCH_COUNTRY_LIST_FAILURE = 'FETCH_COUNTRY_LIST_FAILURE';

export const CLEAR_HF_SUMMARY = 'CLEAR_HF_SUMMARY';

export const FETCH_HF_DASHBOARD_LIST_REQUEST = 'FETCH_HF_DASHBOARD_LIST_REQUEST';
export const FETCH_HF_DASHBOARD_LIST_SUCCESS = 'FETCH_HF_DASHBOARD_LIST_SUCCESS';
export const FETCH_HF_DASHBOARD_LIST_FAILURE = 'FETCH_HF_DASHBOARD_LIST_FAILURE';

export const SET_HF_SUMMARY = 'SET_HF_SUMMARY';
export const CLEAR_HF_DROPDOWN_OPTIONS = 'CLEAR_HF_DROPDOWN_OPTIONS';
