export const FETCH_CUSTOMIZATION_FORM_REQUEST = 'FETCH_CUSTOMIZATION_FORM_REQUEST';
export const FETCH_CUSTOMIZATION_FORM_SUCCESS = 'FETCH_CUSTOMIZATION_FORM_SUCCESS';
export const FETCH_CUSTOMIZATION_FORM_FAILURE = 'FETCH_CUSTOMIZATION_FORM_FAILURE';

export const FETCH_CONSENT_FORM_SUCCESS = 'FETCH_CONSENT_FORM_SUCCESS';
export const FETCH_CONSENT_FORM_FAILURE = 'FETCH_CONSENT_FORM_FAILURE';

export const CLEAR_CONSENT_FORM = 'CLEAR_CONSENT_FORM';

export const FETCH_FORM_META_REQUEST = 'FETCH_FORM_META_REQUEST';
export const FETCH_FORM_META_SUCCESS = 'FETCH_FORM_META_SUCCESS';
export const FETCH_FORM_META_FAILURE = 'FETCH_FORM_META_FAILURE';

export const CLEAR_FORM_JSON = 'CLEAR_FORM_JSON';
export const CLEAR_FORM_META = 'CLEAR_FORM_META';

export const CUSTOMIZE_FORM_REQUEST = 'CUSTOMIZE_FORM_REQUEST';
export const CUSTOMIZE_FORM_SUCCESS = 'CUSTOMIZE_FORM_SUCCESS';
export const CUSTOMIZE_FORM_FAILURE = 'CUSTOMIZE_FORM_FAILURE';

export const DEACTIVATE_CONSENT_FORM_REQUEST = 'DEACTIVATE_CONSENT_FORM_REQUEST';
export const DEACTIVATE_CONSENT_FORM_SUCCESS = 'DEACTIVATE_CONSENT_FORM_SUCCESS';
export const DEACTIVATE_CONSENT_FORM_FAILURE = 'DEACTIVATE_CONSENT_FORM_FAILURE';

export const FETCH_CLINICAL_WORKFLOW_REQUEST = 'FETCH_CLINICAL_WORKFLOW_REQUEST';
export const FETCH_CLINICAL_WORKFLOW_SUCCESS = 'FETCH_CLINICAL_WORKFLOW_SUCCESS';
export const FETCH_CLINICAL_WORKFLOW_FAILURE = 'FETCH_CLINICAL_WORKFLOW_FAILURE';

export const CREATE_WORKFLOW_MODULE_REQUEST = 'CREATE_WORKFLOW_MODULE_REQUEST';
export const CREATE_WORKFLOW_MODULE_SUCCESS = 'CREATE_WORKFLOW_MODULE_SUCCESS';
export const CREATE_WORKFLOW_MODULE_FAILURE = 'CREATE_WORKFLOW_MODULE_FAILURE';

export const UPDATE_WORKFLOW_MODULE_REQUEST = 'UPDATE_WORKFLOW_MODULE_REQUEST';
export const UPDATE_WORKFLOW_MODULE_SUCCESS = 'UPDATE_WORKFLOW_MODULE_SUCCESS';
export const UPDATE_WORKFLOW_MODULE_FAILURE = 'UPDATE_WORKFLOW_MODULE_FAILURE';

export const DELETE_WORKFLOW_MODULE_REQUEST = 'DELETE_WORKFLOW_MODULE_REQUEST';
export const DELETE_WORKFLOW_MODULE_SUCCESS = 'DELETE_WORKFLOW_MODULE_SUCCESS';
export const DELETE_WORKFLOW_MODULE_FAILURE = 'DELETE_WORKFLOW_MODULE_FAILURE';

export const RESET_CLINICAL_WORKFLOW_REQUEST = 'RESET_CLINICAL_WORKFLOW_REQUEST';
