const APPCONSTANTS = {
  APP_TYPE: 'web',
  HASH_ALGORITM: 'sha512',
  AUTHTOKEN: 'at',
  USER_TENANTID: 'uti',
  APP_VERSION: 'av',
  SECRET_TOKEN: 'sat',
  USERNAME: 'un',
  PASSWORD: 'pw',
  REMEMBER_ME: 'rm',
  TENANT_ID: 'ti',
  ENCRYPTION: {
    ALGM: 'aes-256-gcm',
    IV: 'ncd@123',
    SALT: 'ncd@123',
    ITERATION: 2048,
    KEYLEN: 32,
    DIGEST: 'sha512'
  },
  PAGINATION_RANGE: 5,
  INITIAL_PAGE: 1,
  ROWS_PER_PAGE_OF_TABLE: 10,
  FIRST_NAME_LENGTH: 100,
  LAST_NAME_LENGTH: 100,
  FAMILY_NAME_LENGTH: 100,
  SUITE_ACCESS: {
    ADMIN: 'admin',
    CFR: 'cfr'
  },
  ROLES: {
    SUPER_USER: 'SUPER_USER',
    SUPER_ADMIN: 'SUPER_ADMIN',
    HEALTH_FACILITY_ADMIN: 'HEALTH_FACILITY_ADMIN',
    PEER_SUPERVISOR: 'PEER_SUPERVISOR',
    REGION_ADMIN: 'REGION_ADMIN',
    ACCOUNT_ADMIN: 'COUNTY_ADMIN',
    OPERATING_UNIT_ADMIN: 'OPERATING_UNIT_ADMIN',
    LAB_TECHNICIAN: 'LAB_TECHNICIAN',
    REPORT_ADMIN: 'REPORT_ADMIN',
    FACILITY_REPORT_ADMIN: 'FACILITY_REPORT_ADMIN'
  },
  ROUTE_NAMES: {
    REGION: 'region',
    DISTRICT: 'district',
    CHIEFDOM: 'chiefdom',
    HEALTHFACILITY: 'health-facility'
  },
  IS_SIDEMENU_COLLAPSED: 'isSmCollapsed',
  REGIONS_PER_PAGE: 10,
  MEDICATION_LIST_PER_PAGE: 10,
  CHIEFDOM_PER_PAGE: 15,
  SUPERADMINS_PER_PAGE: 10,
  DISTRICT_PER_PAGE: 10,
  HF_PER_PAGE: 15,
  LINK_EXPIRED: 'Link has expired.',
  ALERT: 'Alert',
  PASSWORD_SET_SUCCESS: 'Password has been set successfully.',
  PASSWORD_SET_FAILED: 'Failed to set password. Please try again.',
  PASSWORD_CHANGE_SUCCESS: 'Password has been changed successfully.',
  PASSWORD_CHANGE_FAILED: 'Failed to change the password. Please try again.',
  SUCCESS: 'Success',
  PASSWORD_RESET_EMAIL_SENT_MESSAGE:
    'You will receive the email notification to reset the password if your account exists in our system.',
  OOPS: 'Oops',
  ERROR: 'Error',
  // REGION
  REGION_UPLOAD_SUCCESS: 'Region data uploaded successfully.',
  REGION_UPLOAD_FAILURE: 'Unable to upload the region data. Please try after sometime.',
  REGION_DOWNLOAD_SUCCESS: 'Region data downloaded successfully.',
  REGION_DOWNLOAD_FAILURE: 'Unable to download the region data. Please try after sometime.',
  REGION_CREATION_SUCCESS: 'Region created successfully.',
  REGION_CREATION_ERROR: 'Unable to create region. Please try after sometime.',
  REGION_FETCH_ERROR: 'Unable to load regions. Please try after sometime.',
  REGION_DETAIL_FETCH_ERROR: 'Unable to load region details. Please try after sometime.',
  // ACCOUNT
  ACTIVATE_ACCOUNT_CONFIRMATION: 'Are you sure want to activate the account?',
  ACTIVATE_ACCOUNT_TITLE: 'Activate Account',
  ACCOUNT_ACTIVATE_SUCCESS: 'Account activated successfully.',
  ACCOUNT_ACTIVATE_FAIL: 'Unable to activate the account. Please try after sometime.',
  ACCOUNT_WORKFLOW_MODULE_CREATE_SUCCESS: 'Account workflow module created successfully.',
  ACCOUNT_WORKFLOW_MODULE_CREATE_FAIL: 'Unable to create account workflow module. Please try after sometime.',
  ACCOUNT_WORKFLOW_MODULE_UPDATE_SUCCESS: 'Account workflow module updated successfully.',
  ACCOUNT_WORKFLOW_MODULE_UPDATE_FAIL: 'Unable to update account workflow module. Please try after sometime.',
  ACCOUNT_WORKFLOW_DELETE_TITLE: 'Delete Account workflow',
  ACCOUNT_WORKFLOW_DELETE_CONFIRMATION: 'Are you sure you want to delete the account workflow?',
  ACCOUNT_WORKFLOW_DELETE_SUCCESS: 'Account workflow module deleted successfully.',
  ACCOUNT_WORKFLOW_DELETE_ERROR: 'Unable to delete the account workflow. Please try after sometime.',
  ACCOUNT_WORKFLOW_ALREADY_EXISTS: 'Account workflow name already exists.',
  ACCOUNT_UPDATE_SUCCESS: 'Account summary updated successfully.',
  ACCOUNT_UPDATE_FAIL: 'Unable to update account summary. Please try after sometime.',
  ACCOUNT_DEACTIVATE_SUCCESS: 'Account deactivated successfully.',
  ACCOUNT_DEACTIVATE_FAIL: 'Unable to deactivate the account. Please try after sometime.',
  ACCOUNT_CREATION_SUCCESS: 'Account created successfully.',
  ACCOUNT_CREATION_FAIL: 'Unable to create account. Please try after sometime.',
  ACCOUNT_ADMIN_DELETE_CONFIRMATION: 'Are you sure want to delete account admin?',
  ACCOUNT_ADMIN_DELETE_TITLE: 'Delete Account Admin',
  ACCOUNT_DETAIL_FETCH_ERROR: 'Unable to load account summary. Please try after sometime.',
  ACCOUNT_ADMIN_CREATE_SUCCESS: 'Account admin added successfully.',
  ACCOUNT_ADMIN_CREATE_FAIL: 'Unable to add account admin. Please try after sometime',
  ACCOUNT_ADMIN_UPDATE_SUCCESS: 'Account admin updated successfully.',
  ACCOUNT_ADMIN_UPDATE_FAIL: 'Unable to update account admin. Please try after sometime',
  ACCOUNT_ADMIN_DELETE_SUCCESS: 'Account admin deleted successfully.',
  ACCOUNT_ADMIN_DELETE_FAIL: 'Unable to delete account admin. Please try after sometime.',
  // HF
  HEALTH_FACILITY_LIST_FETCH_ERROR: 'Unable to load health facilities. Please try after sometime.',
  HEALTH_FACILITY_USERS_FETCH_ERROR: 'Unable to load health facility users. Please try after sometime.',
  HEALTH_FACILITY_DETAILS_UPDATE_ERROR: 'Unable to update health facility details. Please try after sometime.',
  HEALTH_FACILITY_DETAILS_UPDATE_SUCCESS: 'Health facility details updated successfully.',
  HEALTH_FACILITY_DETAILS_FETCH_ERROR: 'Unable to load health facility details. Please try after sometime.',
  HEALTH_FACILITY_SUMMARY_FETCH_ERROR: 'Unable to load health facility summary details. Please try after sometime.',
  HEALTH_FACILITY_SUMMARY_UPDATE_ERROR: 'Unable to update health facility summary details. Please try after sometime.',
  HEALTH_FACILITY_CREATION_SUCCESS: 'Health facility created successfully',
  HEALTH_FACILITY_CREATION_ERROR: 'Unable to create health facility. Please try after sometime.',
  HEALTH_FACILITY_USER_CREATE_SUCCESS: 'Health facility user added successfully.',
  HEALTH_FACILITY_USER_CREATE_ERROR: 'Unable to add health facility user. Please try after sometime.',
  HEALTH_FACILITY_USER_UPDATE_SUCCESS: 'Health facility user updated successfully.',
  HEALTH_FACILITY_USER_UPDATE_ERROR: 'Unable to update health facility user. Please try after sometime.',
  HEALTH_FACILITY_USER_DELETE_SUCCESS: 'Health facility user deleted successfully.',
  HEALTH_FACILITY_USER_DELETE_FAIL: 'Unable to delete health facility user. Please try after sometime.',
  HEALTH_FACILITY_USER_DELETE_CONFIRMATION: 'Are you sure you want to delete the health facility user?',
  HEALTH_FACILITY_USER_DELETE_TITLE: 'Delete Health Facility User',
  HEALTH_FACILITY_DELETE_CONFIRMATION:
    'Are you sure you want to delete the health facility? All the users linked to this facility will also be deleted!',
  HEALTH_FACILITY_DELETE_TITLE: 'Delete Health Facility',
  HEALTH_FACILITY_DELETE_SUCCESS: 'Health facility deleted successfully.',
  HEALTH_FACILITY_DELETE_FAIL: 'Unable to delete the health facility. Please try after sometime.',
  CLINICAL_WORKFLOW_FETCH_FAILURE: 'Unable to load the clinical workflows. Please try after sometime.',
  // USER
  CHW_USER_EXCEPTION_HF_CREATE: 'CHW user should not be created in Health facility create',
  SUPER_ADMIN_USER_EXCEPTION_HF_CREATE: 'Existing Super Admin should not be added.',
  SUPER_ADMIN_USER_EXCEPTION_HF_CREATE: 'Existing Super Admin should not be added.',
  PROFILE_DETAIL_ERROR: 'Unable to fetch user details.  Please try after sometime.',
  USER_DETAILS_CREATE_SUCCESS: 'User details created successfully.',
  USER_DETAILS_UPDATE_SUCCESS: 'User details updated successfully.',
  USER_DETAILS_UPDATE_ERROR: 'Unable to update user. Please try after sometime.',
  USER_CREATE_SUCCESS: 'User added successfully.',
  USER_CREATE_ERROR: 'Unable to add user. Please try after sometime.',
  USER_UPDATE_SUCCESS: 'User updated successfully.',
  USER_UPDATE_ERROR: 'Unable to update user. Please try after sometime.',
  USER_DELETE_CONFIRMATION: 'Are you sure you want to delete the user?',
  USER_DELETE_TITLE: 'Delete User',
  USER_DELETE_SUCCESS: 'User deleted successfully.',
  USER_DELETE_FAIL: 'Unable to delete the user. Please try after sometime.',
  USER_DETAIL_FETCH_FAIL: 'Unable to load the user detail. Please try after sometime.',
  USERS_LIST_FETCH_ERROR: 'Unable to load users. Please try after sometime.',
  NO_VILLAGE_FOUND: 'No village available. Villages are already linked to other users.',
  // MEDICATION
  MEDICATION_CREATION_SUCCESS: 'Medication created successfully.',
  MEDICATION_CREATION_ERROR: 'Unable to create medication. Please try after sometime.',
  MEDICATION_FETCH_ERROR: 'Unable to load medications. Please try after sometime.',
  MEDICATION_REENTERED_ERROR: 'You have already entered this medication in the form.',
  RESULT_NAME_REENTERED_ERROR: 'You have already entered this result name in the form.',
  RESULT_UNIT_REENTERED_ERROR: 'You have already entered this range in the form.',
  UNSAVED_CHANGES_MESSAGE: 'Please save your edited changes before submitting.',
  MEDICATION_EXISTS_ERROR: 'This medication is already available in the database.',
  MEDICATION_LIST_FETCH_ERROR: 'Unable to load medications list. Please try after sometime.',
  MEDICATION_UPDATE_SUCCESS: 'Medication updated successfully.',
  MEDICATION_UPDATE_FAIL: 'Unable to update medication. Please try after sometime.',
  MEDICATION_DELETE_SUCCESS: 'Medication deleted successfully.',
  MEDICATION_DELETE_FAIL: 'Unable to delete the medication. Please try after sometime.',
  MEDICATION_DELETE_TITLE: 'Delete Medication',
  MEDICATION_DELETE_CONFIRMATION: 'Are you sure you want to delete the medication?',

  USER_ROLES_FETCH_ERROR: 'Unable to fetch the user roles. Please try again after sometime',

  NETWORK_ERROR: 'Network Error',
  LOGIN_FAILED_TITLE: 'Login failed',
  LOGIN_FAILED_MESSAGE: 'Unable to login. Please try after sometime.',
  CONNECTION_LOST: 'There is an issue with the connection. Please try after sometime.',
  PASSWORD_RULE: 'Password must contain 6 or more characters, including uppercase, lowercase and number characters.',
  ENTER_PASSWORD: 'Please enter new password.',
  ENTER_CONFIRM_PASSWORD: 'Please enter confirm password.',
  PASSWORD_SHOULD_NOT_MATCH_ACC_NAME: `New password should not match the user's account name.`,
  FETCH_SIDEMENU_ERROR: 'Unable to fetch sidemenu. Please try after sometime',
  COMMON_PASSWORDS_ARE_NOT_ALLOWED: 'Common passwords are not allowed.',
  CONFIRM_PASSWORD_SHOULD_MATCH: 'Confirm new password should match with new password.',
  LOGIN_GENERAL_ERROR: 'Unable to login. Please try after sometime.',
  NO_RECORDS_FOUND: 'No records found',
  SEARCH_USER_ERROR: 'Unable to search the admin. Please try after sometime.',

  // form Builder
  FORM_CUSTOMIZATION_SUCCESS: 'Dynamic customization updated successfully.',
  FORM_CUSTOMIZATION_ERROR: 'Unable to update the dynamic customization. Please try after sometime.',
  VALIDITY_OPTIONS: {
    gone: { key: 'gone', label: 'Hide' },
    visible: { key: 'visible', label: 'Show' }
  },

  //

  REGION_TENANT_ERROR: 'Unable to get region information. Please try after sometime.',
  SEARCH_BY_NAME_EMAIL: 'Name / Email',
  SEARCH_BY_NAME: 'Search Name',
  SEARCH_BY_EMAIL: 'Search Email',
  GENDER_OPTIONS: [
    { value: 'Male', label: 'Male' },
    { value: 'Female', label: 'Female' }
  ],
  SESSION_EXPIRED: 'Session got expired. Please login again.',
  LOCKED_USERS_FETCH_ERROR: 'Unable to load the locked users list. Please try after sometime.',
  RESTRICTION_OPTIONS: [
    { value: 'Yes', label: 'Yes' },
    { value: 'No', label: 'No' }
  ],
  ACCOUNT_FETCH_ERROR: 'Unable to load accounts. Please try after sometime.',
  DEACTIVATED_RECORDS_FETCH_ERROR: 'Unable to load deactivated records. Please try after sometime.',

  UNLOCK_USER_SUCCESS: 'User unlocked successfully.',
  UNLOCK_USER_FAIL: 'Unable to unlock the user. Please try after sometime.',

  DEFAULT_CULTURE: { id: 1, name: 'English - India' },
  FORM_ID: 'formId',
  COUNTRY_ID: 'ci',
  COUNTRY_TENANT_ID: 'cti',
  ID: 'id',
  REGION_NAME: 'regionName',
  ACC_ID: 'accId',
  REGION_ADMIN_UPDATE_SUCCESS: 'Region admin updated successfully.',
  REGION_ADMIN_UPDATE_FAIL: 'Unable to update region admin. Please try after sometime.',
  DELETE: 'Delete',
  ADD: 'Add',
  RESET: 'Reset',
  YES: 'Yes',
  NO: 'No',

  // LAB TEST
  LABTEST_CREATION_SUCCESS: 'Lab test created successfully.',
  LABTEST_CREATION_ERROR: 'Unable to create lab tests. Please try after sometime.',
  LABTEST_FETCH_ERROR: 'Unable to load lab tests. Please try after sometime.',
  LABTEST_LIST_FETCH_ERROR: 'Unable to load lab tests list. Please try after sometime.',
  LABTEST_UPDATE_SUCCESS: 'Lab test updated successfully.',
  LABTEST_UPDATE_FAIL: 'Unable to update lab test. Please try after sometime.',
  LABTEST_DELETE_SUCCESS: 'Lab test deleted successfully.',
  LABTEST_DELETE_ERROR: 'Unable to delete the lab test. Please try after sometime.',
  LABTEST_RANGE_DELETE_ERROR: 'Unable to delete the lab test range. Please try after sometime.',
  LABTEST_RANGE_FETCH_ERROR: 'Unable to load the lab test range. Please try after sometime.',
  LABTEST_DELETE_TITLE: 'Delete Lab test',
  LABTEST_DELETE_CONFIRMATION: 'Are you sure you want to delete the lab test?',
  LABT_RESULT_RANGE_DELETE_TITLE: 'Delete Lab test result range',
  LABT_RESULT_RANGE_DELETE_CONFIRMATION: 'Are you sure you want to delete the lab test result range?',
  LABTEST_RESULT_RANGES_CREATE_SUCCESS: 'Labtest result ranges created successfully.',
  LABTEST_RESULT_RANGES_CREATE_FAIL: 'Unable to create lab result ranges. Please try after sometime.',
  LABTEST_RESULT_RANGES_UPDATE_SUCCESS: 'Labtest result ranges updated successfully.',
  LABTEST_RESULT_RANGES_UPDATE_FAIL: 'Unable to update lab result ranges. Please try after sometime.',
  REQUIRED_MANDATORY_FAILED: 'At least two fields need to be mandatory.',

  FORGOT_USER_FAILURE_ERR_MSG: 'Unable to submit the request. Please try after sometime.',
  EMAIL_ALREADY_EXISTS_ERR_MSG: 'Email ID already exists',
  CFR_ERR_MSG: 'Email ID already exists in CFR role',
  SITE_ADMIN_PERMISSION_ERR_MSG: 'You dont have permission to add Site Admin',
  EMAIL_ALREADY_EXISTS_IN_ORG_ERR_MSG: 'Email ID already exists in different organization',
  EMAIL_DUPLICATION_ERR_MSG: `Multiple users can't have same`,
  PHONE_NUMBER_ALREADY_EXISTS_ERR_MSG: 'Phone number already exists',
  PHONE_NUMBER_DUPLICATION_ERR_MSG: `Multiple users can't have same`,
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  LABTEST_REENTERED_ERROR: 'You have already entered this lab test in the form.',
  LABTEST_EXISTS_ERROR: 'This lab test is already available in the regional database.',
  PROGRAM_CREATION_SUCCESS: 'Program created successfully.',
  PROGRAM_CREATION_ERROR: 'Unable to create program. Please try after sometime.',
  PROGRAM_DETAILS_ERROR: 'Unable to fetch program details. Please try after sometime.',
  PROGRAM_UPDATE_SUCCESS: 'Program updated successfully.',
  PROGRAM_UPDATE_ERROR: 'Unable to update program. Please try after sometime.',
  PROGRAM_DELETE_TITLE: 'Delete Program',
  PROGRAM_DELETE_CONFIRMATION: 'Are you sure you want to delete the program?',
  PROGRAM_FETCH_ERROR: 'Unable to load programs. Please try after sometime.',
  PROGRAM_DELETE_SUCCESS: 'Program deleted successfully.',
  PROGRAM_DELETE_ERROR: 'Unable to delete the program. Please try after sometime.',

  // consent form values
  FETCH_CONSENT_FORM_ERROR: 'Unable to fetch the consent form data. Please try after sometime.',
  CONSENT_FORM_CUSTOMIZATION_SUCCESS: 'consent form updated successfully.',
  CONSENT_FORM_CUSTOMIZATION_ERROR: 'consent form updation failed. Please try after sometime.',
  CONSENT_FORM_EMPTY_ERROR: 'Consent data should not be empty.',
  DEACTIVATE_CONSENT_SUCCESS: 'consent form deleted successfully.',
  DEACTIVATE_CONSENT_FAILURE: 'consent form deletion failed. Please try after sometime.',
  DEACTIVATE_CONSENT_NO_DATA: 'consent data not found. Please try after sometime.',
  DELETE_CONSENT_TITLE: 'Delete confirmation',
  DELETE_CONSENT_CONFIRMATION: 'Are you sure you want to delete the county consent form?',
  FETCH_FORM_META_ERROR: 'Unable to fetch the form meta data. Please try after sometime.',

  REGION_CUSTOMIZATION_SCREENS: [
    { name: 'Screening Form' },
    { name: 'Enrollment Form' },
    { name: 'Assessment Form', isCustomIconInvisible: true }
  ],
  NO_FAMILY: 'NO_FAMILY',
  INVALID_CREDENTIALS: 'Invalid credentials',
  DEACTIVATE_REASON: [
    { label: 'Unable to pay', value: 'Unable to pay' },
    { label: 'Contract expired', value: 'Contract expired' },
    { label: 'Site closure', value: 'Site closure' },
    { label: 'Inactive site', value: 'Inactive site' },
    { label: 'Other', value: 'Other' }
  ],
  SITE_ROLES: [
    { value: 'HEALTH_COACH', label: 'Health Coach' },
    { value: 'HEALTH_SCREENER', label: 'Health Screener' },
    { value: 'HRIO', label: 'HRIO' },
    { value: 'LAB_TECHNICIAN', label: 'Lab Technician' },
    { value: 'NUTRITIONIST', label: 'Nutritionist' },
    { value: 'PHARMACIST', label: 'Pharmacist' },
    { value: 'NURSE', label: 'Nurse' },
    { value: 'PHYSICIAN_PRESCRIBER', label: 'Physician Prescriber' },
    { value: 'PROVIDER', label: 'Provider' },
    { value: 'COUNSELOR', label: 'Counselor' },
    { value: 'SITE_ADMIN', label: 'Site Admin' }
  ],
  // utils

  MONTHS: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ],
  DISABLED_FIELD_TYPES_FOR_REGION_CUSTOMIZATION: ['fieldName', 'title', 'optionsList', 'inputType']
};

export const NAME_CONSTANTS = {
  region: 'Region',
  county: 'County',
  subCounty: 'Sub County',
  healthFacility: 'Health Facility'
};

export const ROLE_LABELS = {
  [APPCONSTANTS.ROLES.SUPER_USER]: 'Super User',
  [APPCONSTANTS.ROLES.SUPER_ADMIN]: 'Super Admin',
  [APPCONSTANTS.ROLES.HEALTH_FACILITY_ADMIN]: 'Admin',
  [APPCONSTANTS.ROLES.PEER_SUPERVISOR]: 'Peer Supervisor'
};

export default APPCONSTANTS;
