export const FETCH_CHIEFDOM_DASHBOARD_LIST_REQUEST = 'FETCH_CHIEFDOM_DASHBOARD_LIST_REQUEST';
export const FETCH_CHIEFDOM_DASHBOARD_LIST_SUCCESS = 'FETCH_CHIEFDOM_DASHBOARD_LIST_SUCCESS';
export const FETCH_CHIEFDOM_DASHBOARD_LIST_FAILURE = 'FETCH_CHIEFDOM_DASHBOARD_LIST_FAILURE';

export const FETCH_CHIEFDOM_DETAIL_REQUEST = 'FETCH_CHIEFDOM_DETAIL_REQUEST';
export const FETCH_CHIEFDOM_DETAIL_SUCCESS = 'FETCH_CHIEFDOM_DETAIL_SUCCESS';
export const FETCH_CHIEFDOM_DETAIL_FAILURE = 'FETCH_CHIEFDOM_DETAIL_FAILURE';

export const SEARCH_CHIEFDOM_USER_SUCCESS = 'SEARCH_CHIEFDOM_USER_SUCCESS';

export const FETCH_CHIEFDOM_LIST_REQUEST = 'FETCH_CHIEFDOM_LIST_REQUEST';
export const FETCH_CHIEFDOM_LIST_SUCCESS = 'FETCH_CHIEFDOM_LIST_SUCCESS';
export const FETCH_CHIEFDOM_LIST_FAILURE = 'FETCH_CHIEFDOM_LIST_FAILURE';

export const CREATE_CHIEFDOM_REQUEST = 'CREATE_CHIEFDOM_REQUEST';
export const CREATE_CHIEFDOM_SUCCESS = 'CREATE_CHIEFDOM_SUCCESS';
export const CREATE_CHIEFDOM_FAILURE = 'CREATE_CHIEFDOM_FAILURE';

export const UPDATE_CHIEFDOM_REQUEST = 'UPDATE_CHIEFDOM_REQUEST';
export const UPDATE_CHIEFDOM_SUCCESS = 'UPDATE_CHIEFDOM_SUCCESS';
export const UPDATE_CHIEFDOM_FAILURE = 'UPDATE_CHIEFDOM_FAILURE';

export const UPDATE_CHIEFDOM_ADMIN_REQUEST = 'UPDATE_CHIEFDOM_ADMIN_REQUEST';
export const UPDATE_CHIEFDOM_ADMIN_SUCCESS = 'UPDATE_CHIEFDOM_ADMIN_SUCCESS';
export const UPDATE_CHIEFDOM_ADMIN_FAILURE = 'UPDATE_CHIEFDOM_ADMIN_FAILURE';

export const CREATE_CHIEFDOM_ADMIN_REQUEST = 'CREATE_CHIEFDOM_ADMIN_REQUEST';
export const CREATE_CHIEFDOM_ADMIN_SUCCESS = 'CREATE_CHIEFDOM_ADMIN_SUCCESS';
export const CREATE_CHIEFDOM_ADMIN_FAILURE = 'CREATE_CHIEFDOM_ADMIN_FAILURE';

export const DELETE_CHIEFDOM_ADMIN_REQUEST = 'DELETE_CHIEFDOM_ADMIN_REQUEST';
export const DELETE_CHIEFDOM_ADMIN_SUCCESS = 'DELETE_CHIEFDOM_ADMIN_SUCCESS';
export const DELETE_CHIEFDOM_ADMIN_FAILURE = 'DELETE_CHIEFDOM_ADMIN_FAILURE';

export const FETCH_CHIEFDOM_BY_ID_REQUEST = 'FETCH_CHIEFDOM_BY_ID_REQUEST';
export const FETCH_CHIEFDOM_BY_ID_SUCCESS = 'FETCH_CHIEFDOM_BY_ID_SUCCESS';
export const FETCH_CHIEFDOM_BY_ID_FAILURE = 'FETCH_CHIEFDOM_BY_ID_FAILURE';

export const FETCH_CHIEFDOM_ADMIN_BY_ID_REQUEST = 'FETCH_CHIEFDOM_ADMIN_BY_ID_REQUEST';
export const FETCH_CHIEFDOM_ADMIN_BY_ID_SUCCESS = 'FETCH_CHIEFDOM_ADMIN_BY_ID_SUCCESS';
export const FETCH_CHIEFDOM_ADMIN_BY_ID_FAILURE = 'FETCH_CHIEFDOM_ADMIN_BY_ID_FAILURE';

export const CLEAR_CHIEFDOM_DETAIL = 'CLEAR_CHIEFDOM_DETAIL';

export const SET_CHIEFDOM_DETAILS = 'SET_CHIEFDOM_DETAILS';

export const CLEAR_CHIEFDOM_LIST = 'CLEAR_CHIEFDOM_LIST';

export const CLEAR_CHIEFDOM_ADMIN_LIST = 'CLEAR_CHIEFDOM_ADMIN_LIST';

export const FETCH_CHIEFDOM_DROPDOWN_REQUEST = 'FETCH_CHIEFDOM_DROPDOWN_REQUEST';
export const FETCH_CHIEFDOM_DROPDOWN_SUCCESS = 'FETCH_CHIEFDOM_DROPDOWN_SUCCESS';
export const FETCH_CHIEFDOM_DROPDOWN_FAIL = 'FETCH_CHIEFDOM_DROPDOWN_FAIL';

export const CLEAR_DROPDOWN_VALUES = 'CLEAR_DROPDOWN_VALUES';
