export const FETCH_REGIONS_REQUEST = 'FETCH_REGIONS_REQUEST';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_FAILURE = 'FETCH_REGIONS_FAILURE';

export const FETCH_REGION_DETAIL_REQUEST = 'FETCH_REGION_DETAIL_REQUEST';
export const FETCH_REGION_DETAIL_SUCCESS = 'FETCH_REGION_DETAIL_SUCCESS';
export const FETCH_REGION_DETAIL_FAILURE = 'FETCH_REGION_DETAIL_FAILURE';

export const FETCH_COUNTRY_DETAILS_REQUEST = 'FETCH_REGION_DETAILS_REQUEST';
export const FETCH_COUNTRY_DETAILS_SUCCESS = 'FETCH_COUNTRY_DETAILS_SUCCESS';
export const FETCH_COUNTRY_DETAILS_FAILURE = 'FETCH_COUNTRY_DETAILS_FAILURE';

export const CREATE_REGION_REQUEST = 'CREATE_REGION_REQUEST';
export const CREATE_REGION_SUCCESS = 'CREATE_REGION_SUCCESS';
export const CREATE_REGION_FAILURE = 'CREATE_REGION_FAILURE';

export const FETCH_CLIENT_REGISTRY_STATUS_REQUEST = 'FETCH_CLIENT_REGISTRY_STATUS_REQUEST';
export const FETCH_CLIENT_REGISTRY_STATUS_SUCCESS = 'FETCH_CLIENT_REGISTRY_STATUS_SUCCESS';
export const FETCH_CLIENT_REGISTRY_STATUS_FAIL = 'FETCH_CLIENT_REGISTRY_STATUS_FAIL';
export const CLEAR_CLIENT_REGISTRY_STATUS = 'CLEAR_CLIENT_REGISTRY_STATUS';

export const SET_REGION_DETAILS = 'SET_REGION_DETAILS';

export const CLEAR_REGION_DETAIL = 'CLEAR_REGION_DETAIL';

export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';

export const DOWNLOAD_FILE_REQUEST = 'DOWNLOAD_FILE_REQUEST';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAILURE = 'DOWNLOAD_FILE_FAILURE';
