export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';

export const DOWNLOAD_FILE_REQUEST = 'DOWNLOAD_FILE_REQUEST';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAILURE = 'DOWNLOAD_FILE_FAILURE';

export const REGION_DETAILS_REQUEST = 'REGION_DETAILS_REQUEST';
export const REGION_DETAILS_SUCCESS = 'REGION_DETAILS_SUCCESS';
export const REGION_DETAILS_FAILURE = 'REGION_DETAILS_FAILURE';
