export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FETCH_LOGGED_IN_USER_REQUEST = 'FETCH_LOGGED_IN_USER_REQUEST';
export const FETCH_LOGGED_IN_USER_SUCCESS = 'FETCH_LOGGED_IN_USER_SUCCESS';
export const FETCH_LOGGED_IN_USER_FAILURE = 'FETCH_LOGGED_IN_USER_FAILURE';

export const FETCH_USER_BY_EMAIL = 'FETCH_USER_BY_EMAIL';
export const FETCH_USER_BY_EMAIL_SUCCESS = 'FETCH_USER_BY_EMAIL_SUCCESS';
export const FETCH_USER_BY_EMAIL_FAIL = 'FETCH_USER_BY_EMAIL_FAIL';

export const FETCH_USER_ROLES_REQUEST = 'FETCH_USER_ROLES_REQUEST';
export const FETCH_USER_ROLES_SUCCESS = 'FETCH_USER_ROLES_SUCCESS';
export const FETCH_USER_ROLES_FAILURE = 'FETCH_USER_ROLES_FAILURE';

export const ADD_USER_TENANT_ID = 'ADD_USER_TENANT_ID';
export const REMOVE_USER_TENANT_ID = 'REMOVE_USER_TENANT_ID';

export const SESSION_TIMEDOUT = 'SESSION_TIMEDOUT';
export const RESET_STORE = 'RESET_STORE';

export const AUTH_TOKEN = 'AUTH_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const FETCH_USER_BY_ID_REQUEST = 'FETCH_USER_BY_ID_REQUEST';
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_FAILURE = 'FETCH_USER_BY_ID_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const CHANGE_OWN_PASSWORD_REQUEST = 'CHANGE_OWN_PASSWORD_REQUEST';
export const CHANGE_OWN_PASSWORD_SUCCESS = 'CHANGE_OWN_PASSWORD_SUCCESS';
export const CHANGE_OWN_PASSWORD_FAILURE = 'CHANGE_OWN_PASSWORD_FAILURE';

export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAILURE = 'USER_FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const GET_USERNAME_FOR_PASSWORD_RESET = 'GET_USERNAME_FOR_PASSWORD_RESET';
export const GET_USERNAME_FOR_PASSWORD_RESET_SUCCESS = 'GET_USERNAME_FOR_PASSWORD_RESET_SUCCESS';
export const GET_USERNAME_FOR_PASSWORD_RESET_FAIL = 'GET_USERNAME_FOR_PASSWORD_RESET_FAIL';
