export const FETCH_BRANCH_LIST_REQUEST = 'FETCH_BRANCH_LIST_REQUEST';
export const FETCH_BRANCH_LIST_SUCCESS = 'FETCH_BRANCH_LIST_SUCCESS';
export const FETCH_BRANCH_LIST_FAILURE = 'FETCH_BRANCH_LIST_FAILURE';

export const CREATE_BRANCH_REQUEST = 'CREATE_BRANCH_REQUEST';
export const CREATE_BRANCH_SUCCESS = 'CREATE_BRANCH_SUCCESS';
export const CREATE_BRANCH_FAILURE = 'CREATE_BRANCH_FAILURE';

export const UPDATE_BRANCH_REQUEST = 'UPDATE_BRANCH_REQUEST';
export const UPDATE_BRANCH_SUCCESS = 'UPDATE_BRANCH_SUCCESS';
export const UPDATE_BRANCH_FAILURE = 'UPDATE_BRANCH_FAILURE';

export const CLEAR_BRANCH_LIST = 'CLEAR_BRANCH_LIST';
