export const UPLOAD_FILE_REQUEST_COM = 'UPLOAD_FILE_REQUEST_COM';
export const UPLOAD_FILE_SUCCESS_COM = 'UPLOAD_FILE_SUCCESS_COM';
export const UPLOAD_FILE_FAILURE_COM = 'UPLOAD_FILE_FAILURE_COM';

export const DOWNLOAD_FILE_REQUEST_COM = 'DOWNLOAD_FILE_REQUEST_COM';
export const DOWNLOAD_FILE_SUCCESS_COM = 'DOWNLOAD_FILE_SUCCESS_COM';
export const DOWNLOAD_FILE_FAILURE_COM = 'DOWNLOAD_FILE_FAILURE_COM';

export const REGION_DETAILS_REQUEST_COM = 'REGION_DETAILS_REQUEST_COM';
export const REGION_DETAILS_SUCCESS_COM = 'REGION_DETAILS_SUCCESS_COM';
export const REGION_DETAILS_FAILURE_COM = 'REGION_DETAILS_FAILURE_COM';

export const SET_REGION_DETAILS_COM = 'SET_REGION_DETAILS_COM';
