export const FETCH_DISTRICT_LIST_REQUEST = 'FETCH_DISTRICT_LIST_REQUEST';
export const FETCH_DISTRICT_LIST_SUCCESS = 'FETCH_DISTRICT_LIST_SUCCESS';
export const FETCH_DISTRICT_LIST_FAILURE = 'FETCH_DISTRICT_LIST_FAILURE';

export const CREATE_DISTRICT_REQUEST = 'CREATE_DISTRICT_REQUEST';
export const CREATE_DISTRICT_SUCCESS = 'CREATE_DISTRICT_SUCCESS';
export const CREATE_DISTRICT_FAILURE = 'CREATE_DISTRICT_FAILURE';

export const CREATE_DISTRICT_ADMIN_FAIL = 'CREATE_DISTRICT_ADMIN_FAIL';
export const FETCH_DISTRICT_DETAIL_REQUEST = 'FETCH_DISTRICT_DETAIL_REQUEST';
export const SEACRH_DISTRICT_USER_SUCCESS = 'SEACRH_DISTRICT_USER_SUCCESS';
export const FETCH_DISTRICT_DETAIL_SUCCESS = 'FETCH_DISTRICT_DETAIL_SUCCESS';
export const FETCH_DISTRICT_DETAIL_FAILURE = 'FETCH_DISTRICT_DETAIL_FAILURE';

export const FETCH_DISTRICT_DASHBOARD_LIST_REQUEST = 'FETCH_DISTRICT_DASHBOARD_LIST_REQUEST';
export const FETCH_DISTRICT_DASHBOARD_LIST_SUCCESS = 'FETCH_DISTRICT_DASHBOARD_LIST_SUCCESS';
export const FETCH_DISTRICT_DASHBOARD_LIST_FAIL = 'FETCH_DISTRICT_DASHBOARD_LIST_FAIL';

export const UPDATE_DISTRICT_DETAIL_REQUEST = 'UPDATE_DISTRICT_DETAIL_REQUEST';
export const UPDATE_DISTRICT_DETAIL_SUCCESS = 'UPDATE_DISTRICT_DETAIL_SUCCESS';
export const UPDATE_DISTRICT_DETAIL_FAIL = 'UPDATE_DISTRICT_DETAIL_FAIL';

export const UPDATE_DISTRICT_ADMIN_REQUEST = 'UPDATE_DISTRICT_ADMIN_REQUEST';
export const UPDATE_DISTRICT_ADMIN_SUCCESS = 'UPDATE_DISTRICT_ADMIN_SUCCESS';
export const UPDATE_DISTRICT_ADMIN_FAIL = 'UPDATE_DISTRICT_ADMIN_FAIL';

export const CREATE_DISTRICT_ADMIN_REQUEST = 'CREATE_DISTRICT_ADMIN_REQUEST';
export const CREATE_DISTRICT_ADMIN_SUCCESS = 'CREATE_DISTRICT_ADMIN_SUCCESS';

export const DELETE_DISTRICT_ADMIN_REQUEST = 'DELETE_DISTRICT_ADMIN_REQUEST';
export const DELETE_DISTRICT_ADMIN_SUCCESS = 'DELETE_DISTRICT_ADMIN_SUCCESS';
export const DELETE_DISTRICT_ADMIN_FAIL = 'DELETE_DISTRICT_ADMIN_FAIL';

export const ACTIVATE_ACCOUNT_REQUEST = 'ACTIVATE_ACCOUNT_REQUEST';
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAIL = 'ACTIVATE_ACCOUNT_FAIL';

export const REMOVE_DEACTIVATED_ACCOUNT_LIST = 'REMOVE_DEACTIVATED_ACCOUNT_LIST';

export const DEACTIVATE_DISTRICT_REQUEST = 'DEACTIVATE_DISTRICT_REQUEST';
export const DEACTIVATE_DISTRICT_SUCCESS = 'DEACTIVATE_DISTRICT_SUCCESS';
export const DEACTIVATE_DISTRICT_FAIL = 'DEACTIVATE_DISTRICT_FAIL';

export const FETCH_DISTRICT_OPTIONS_REQUEST = 'FETCH_DISTRICT_OPTIONS_REQUEST';
export const FETCH_DISTRICT_OPTIONS_SUCCESS = 'FETCH_DISTRICT_OPTIONS_SUCCESS';
export const FETCH_DISTRICT_OPTIONS_FAILURE = 'FETCH_DISTRICT_OPTIONS_FAILURE';

export const CLEAR_DISTRICT_DETAILS = 'CLEAR_DISTRICT_DETAILS';

export const SET_DISTRICT_DETAILS = 'SET_DISTRICT_DETAILS';

export const CLEAR_DISTRICT_LIST = 'CLEAR_DISTRICT_LIST';

export const CLEAR_DISTRICT_ADMIN = 'CLEAR_DISTRICT_ADMIN';

export const CREATE_COUNTY_WORKFLOW_MODULE_REQUEST = 'CREATE_COUNTY_WORKFLOW_MODULE_REQUEST';
export const CREATE_COUNTY_WORKFLOW_MODULE_SUCCESS = 'CREATE_COUNTY_WORKFLOW_MODULE_SUCCESS';
export const CREATE_COUNTY_WORKFLOW_MODULE_FAILURE = 'CREATE_COUNTY_WORKFLOW_MODULE_FAILURE';

export const UPDATE_COUNTY_WORKFLOW_MODULE_REQUEST = 'UPDATE_COUNTY_WORKFLOW_MODULE_REQUEST';
export const UPDATE_COUNTY_WORKFLOW_MODULE_SUCCESS = 'UPDATE_COUNTY_WORKFLOW_MODULE_SUCCESS';
export const UPDATE_COUNTY_WORKFLOW_MODULE_FAILURE = 'UPDATE_COUNTY_WORKFLOW_MODULE_FAILURE';

export const DELETE_COUNTY_WORKFLOW_MODULE_REQUEST = 'DELETE_COUNTY_WORKFLOW_MODULE_REQUEST';
export const DELETE_COUNTY_WORKFLOW_MODULE_SUCCESS = 'DELETE_COUNTY_WORKFLOW_MODULE_SUCCESS';
export const DELETE_COUNTY_WORKFLOW_MODULE_FAILURE = 'DELETE_COUNTY_WORKFLOW_MODULE_FAILURE';

export const RESET_CLINICAL_WORKFLOW_REQUEST = 'RESET_CLINICAL_WORKFLOW_REQUEST';
