export const FETCH_SIDEMENU_REQUEST = 'FETCH_SIDEMENU_REQUEST';
export const FETCH_SIDEMENU_SUCCESS = 'FETCH_SIDEMENU_SUCCESS';
export const FETCH_SIDEMENU_FAILURE = 'FETCH_SIDEMENU_FAILURE';

export const CLEAR_SIDEMENU = 'CLEAR_SIDEMENU';

export const SET_LABELNAME = 'SET_LABELNAME';
export const CLEAR_LABELNAME = 'CLEAR_LABELNAME';
