export const FETCH_SIDEMENU_REQUEST = 'FETCH_SIDEMENU_REQUEST';
export const FETCH_SIDEMENU_SUCCESS = 'FETCH_SIDEMENU_SUCCESS';
export const FETCH_SIDEMENU_FAILURE = 'FETCH_SIDEMENU_FAILURE';

export const SET_SIDEMENU = 'SET_FORMATTED_SIDEMENU';

export const CLEAR_SIDEMENU = 'CLEAR_SIDEMENU';
