export const FETCH_CUSTOMIZATION_FORM_REQUEST = 'FETCH_CUSTOMIZATION_FORM_REQUEST_COM';
export const FETCH_CUSTOMIZATION_FORM_SUCCESS = 'FETCH_CUSTOMIZATION_FORM_SUCCESS_COM';
export const FETCH_CUSTOMIZATION_FORM_FAILURE = 'FETCH_CUSTOMIZATION_FORM_FAILURE_COM';

export const FETCH_CONSENT_FORM_SUCCESS = 'FETCH_CONSENT_FORM_SUCCESS_COM';
export const FETCH_CONSENT_FORM_FAILURE = 'FETCH_CONSENT_FORM_FAILURE_COM';

export const CLEAR_CONSENT_FORM = 'CLEAR_CONSENT_FORM_COM';

export const FETCH_FORM_META_REQUEST = 'FETCH_FORM_META_REQUEST_COM';
export const FETCH_FORM_META_SUCCESS = 'FETCH_FORM_META_SUCCESS_COM';
export const FETCH_FORM_META_FAILURE = 'FETCH_FORM_META_FAILURE_COM';

export const CLEAR_FORM_JSON = 'CLEAR_FORM_JSON_COM';
export const CLEAR_FORM_META = 'CLEAR_FORM_META_COM';

export const CUSTOMIZE_FORM_REQUEST = 'CUSTOMIZE_FORM_REQUEST_COM';
export const CUSTOMIZE_FORM_SUCCESS = 'CUSTOMIZE_FORM_SUCCESS_COM';
export const CUSTOMIZE_FORM_FAILURE = 'CUSTOMIZE_FORM_FAILURE_COM';

export const DEACTIVATE_CONSENT_FORM_REQUEST = 'DEACTIVATE_CONSENT_FORM_REQUEST_COM';
export const DEACTIVATE_CONSENT_FORM_SUCCESS = 'DEACTIVATE_CONSENT_FORM_SUCCESS_COM';
export const DEACTIVATE_CONSENT_FORM_FAILURE = 'DEACTIVATE_CONSENT_FORM_FAILURE_COM';
